# PDS - Lab 6 - Numpy and Scipy

## A. Numpy

Import numpy to start working with the examples below:


In [1]:
import numpy as np

### A.1. Arrays

A **numpy array** is a grid of values, all of the same type, and is indexed by a tuple of non negative integers. 

- The number of dimensions is the **rank** of the array; 
- The **shape** of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from Python lists, and access elements using square brackets:

In [2]:
a = np.array([1, 2, 3 , 4, 5])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            
print(a[0], a[1], a[2])   
a[0] = 5                  # Change an element of the array
print(a)                  

<class 'numpy.ndarray'>
(5,)
1 2 3
[5 2 3 4 5]


In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])    # Create a rank 2 array
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   

(4, 3)
1 2 4


**1.** Numpy provides many functions to create arrays. Create an array of zeros and print its type:

In [5]:
zeroes = np.zeros((1,10))

In [6]:
type(zeroes)

numpy.ndarray

**2.** We can also create an array with constant values. Create a 2x2 matrix with all entries equal to seven.

In [11]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

**3.** Create a matrix filled with randomly generated numbers.

In [12]:
np.random.random((5,5))

array([[0.69570305, 0.77070783, 0.71074033, 0.69191131, 0.41733283],
       [0.51313083, 0.02021355, 0.18846714, 0.85424309, 0.64434328],
       [0.19178574, 0.1276289 , 0.85925644, 0.5631713 , 0.23308185],
       [0.33460352, 0.16894285, 0.62030427, 0.29069386, 0.90328381],
       [0.84789619, 0.68182989, 0.48393007, 0.48080159, 0.89464399]])

### A.2. Array indexing

Numpy offers several ways to index into arrays.

- **Slicing:** Similar to Python lists, numpy arrays can be sliced. 

*Since arrays may be multidimensional, you must specify a slice for each dimension of the array.*

In [49]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

**4.** Use slicing to pull out the subarray consisting of the last 3 elements of the first 2 rows.

In [50]:
a[:2, -3:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

**You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.**

**5.** Return the second column of 'a' as (1) an array and (2) a multidimensional array.

In [51]:
a[:,1]

array([ 2,  7, 12])

In [52]:
a[:, 1:2]

array([[ 2],
       [ 7],
       [12]])

**When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.** 

**6.** Print the diagonal elements of a.

In [53]:
a.diagonal()

array([ 1,  7, 13])

**One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix.** 

**7.** Add 10 to one element from each row of 'a' using the indices in b. 

*Tip: the method np.arange(n) may be helpful.*

In [46]:
# Create an array of indices
b = np.array([0,2,4])

np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [47]:
a[np.arange(len(a)), b] += 10 
a

array([[11,  2,  3,  4,  5],
       [ 6,  7, 18,  9, 10],
       [11, 12, 13, 14, 25]])

### A.3. Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. 

**8.** Find the elements of 'a' that are bigger than 2.
- Firstly, find a boolean multidemnsional array of the same shape as 'a' indidcating if an element is greater than 2. 
- Secondly, use this matrix to return the values from 'a' that are greater than 2.


In [54]:
a>2

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [55]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### A.4. Array Math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module. 

**9.** Check the results of adding and multiplying x and y.

In [57]:
x = np.array([[-10,-20],[-30,-40]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [58]:
x+y

array([[ -5., -14.],
       [-23., -32.]])

**10.** Compute the inner product of x and y.

In [59]:
x*y

array([[ -50., -120.],
       [-210., -320.]])

You can find the full list of mathematical functions provided by numpy in the documentation, see https://docs.scipy.org/doc/numpy/reference/routines.math.html.

**Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays.** 

**11.** Create a 5 x 5 square matrix of the numbers 1 to 25 from an array of the number 1 to 25.

In [64]:
matrix_1_to_25 = np.arange(1, 26).reshape((5,5))

**A simple example of this type of operation is transposing a matrix.**

**12.** Transpose the matrix you created on 11.

In [65]:
matrix_1_to_25.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

Numpy provides many more functions for manipulating arrays; you can see the full list https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html 

**13.** Add the constant vector v to each row of the matrix x.

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

For more information on broadcasting, try reading the explanation from the documentation, see https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html.

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation, https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs.

> ### Why should we bother using Numpy?

**14.** Using python create a function list_adder that will take two lists, and return a list where each element is the sum of the elemets in that position of the two original lists. Basically, your function will add the elements of your lists together to create a new list.

**15.** Create a funtion numpy adder that adds to numpy arrays together and returns the result array.

Run the code below to test the time it takes to run the two functions.

In [ ]:
import time
import random


x = range(10000000) # create large list
y = [random.random() for i in x] # create large random list

# test python function
t1 = time.time()
list_adder(x,y)
time_python = time.time() - t1
print(f"Python time :{time_python} s")

# test numpy function
x = np.array(x)
y = np.array(y)
t1 = time.time()
numpy_adder(x,y)
time_numpy = time.time() - t1
print(f"Numpy time :{time_numpy} s")
print(f"Numpy is {time_python/time_numpy} times faster")

### Additional numpy exercises

Use the numpy finctions unique and sort to find the 2nd highest value in the np.array 'y'.

Create an array z that is the same as the array y except with a maximum value of 50 (all values above 50 are replaced with 50).

Convert the multidimenisional array below into a 1 dimensional array which is equal to all the rows connected.

Create an array containing the moving average of size 3 of the vector y.

## B. Scipy

The SciPy library of Python is built to work with NumPy arrays and provides many user-friendly and efficient numerical practices such as routines for numerical integration and optimization.

### Linear Algebra Operations in SciPy

The module for standard Linear Algebra operations is known as scipy.linalg and you are required to import it well before any operation using the following command operation:

In [ ]:
from scipy import linalg

### B.1. Solving a Linear System

Solving linear systems of equations is straightforward using the scipy command **linalg.solve**. This command expects an input matrix and a right-hand-side vector. The solution vector is then computed. An option for entering a symmetric matrix is offered which can speed up the processing when applicable. As an example, suppose it is desired to solve the following simultaneous equations:

- 5x +2y +5z = 30
- 2x + 5y + z = 18
- 2x +3y +8z = 3

**16.** Solve using linalg.solve, first convert to the form Ax = B, then provide A and B to linalg.solve:

**17.** Check that your solution is correct using linear alegbra.


**18.** Find the solution as the dot product of the inverse of A and B.

### B.2. Random Variables

**19.** Create a 50 x 2 array of random variables drawn from the normal distribution with the values of loc = 5 and scale = 10.

**20.** Report the **mean** and **standard deviation** of each column.

**21.** Perform a t test to check if the columns mean values are equal to 5.

**22.** Perform a t test to check if the columns have different mean values.

### B.3. Fitting Distributions to data

An important task of a Data Scientist is to **find the appropriate distribution** that best describes our observation of events. Scipy makes this task easy. Let us see an example.

**23.** First let us start by creating a sample data set with 500 points (a numpy array called 'x').

**24.** From scippy.stats import the **vonmises** library and create an array 'y' of the same size as 'x' with values drawn for this distribution and a parameter value of 5.

**25.** Multiple all values of 'y' by 100 and convert them to integers.

**26.** Fit a gamma distribution to 'y'.

**27.** Generate values for a new series 'g' based upon the input values of 'x' and your fitted gamma distribution.

Run the cell below to plot a historgram of our data against a pdf of the gamma distribution we fitted.

In [ ]:
import matplotlib.pyplot as plt
plt.plot(g * size, label='gamma')
plt.xlim(1,100)

h = plt.hist(y, bins=range(100),color='gray')
plt.show()

### B.4. Sparse Matrices

A dense matrix is a mathematical object that stores a 2D array of values.

**Why should we care in using sparse matrices?**

Used memory in the declaration of a matrix scales like n*n, small example (double precision matrix):

In [2]:
# import sparse module from SciPy package 
from scipy import sparse
# import uniform module to create random numbers
from scipy.stats import uniform
# import NumPy
import numpy as np

In [3]:
# row indices
row_ind = np.array([0, 1, 1, 3, 4])
# column indices
col_ind = np.array([0, 2, 4, 3, 4])
# data to be stored in COO sparse matrix
data = np.array([1, 2, 3, 4, 5], dtype=float)

We can use sparse.coo_matrix to create a sparse matrix. It takes data and the row and column index tuple as arguments.

In [5]:
# create COO sparse matrix from three arrays


coo_matrix has lots of useful functions including function to convert coo_matrix to other sparse matrices and also to dense matrix. Use the function toarray to see the 2d-array of the sparse matrix that we just created.

### How much space do we gain by storing a big sparse matrix in SciPy.sparse?

**One of the real uses of sparse matrix is the huge space reduction to store sparse matrices.** 

Let us create a bigger full matrix and see how much we gain by storing it as sparse matrix.

In [ ]:
np.random.seed(seed=42)
data = uniform.rvs(size=1000000, loc = 0, scale=2)
data = np.reshape(data, (10000, 100))
data.shape
data.nbytes

In [ ]:
data[data <= 1] = 0
data_size = data.nbytes/(1024**2)
print('Size of full matrix with zeros: '+ '%3.2f' %data_size + ' MB')

We can see the size of full matrix of size 1 million elements with half of them with values zero is about 80 MB.

In [ ]:
data_csr = sparse.csr_matrix(data)
data_csr_size = data_csr.data.size/(1024**2)
print('Size of sparse csr_matrix: '+ '%3.2f' %data_csr_size + ' MB')